### ISSUE TITLE
How to configure the assets/publish command?

### ISSUE THREAD

**Issue by blancsys** [SAM-IT/yii2-static-assets#5]
Hi, this is a cool project!

I want to use the building/publishing of assets (only). 

I mean, I want to be able to execute:
```
./yii staticAssets/assets/publish build12345
```
However, when I try to execute that command, I get:
```
Unknown command: staticAssets/assets/publish
```

I have already updated composer. I mean, I can see the vendor/sam-it/yii2-static-assets directory.

How can I configure Yii to locate the commands provided by you?

Thank you very much!

**Comment by SamMousa** [comment]
Hmm, it should autoload...
The `composer.json` file contains the bootstrap directive for that is used by Yii to run the module bootstrap, which in turn registers the module.

Alternatively, if that doesn't work, you can manually configure the module in your (console) application config.

**Comment by blancsys** [comment]
Thanks for reply so quick! For some reason, it seems like autoloading is not working for me.

Could you please provide me a sample of how to configure the StaticsAsset module in config/console.php?

Thank you very much in advance!

**Comment by SamMousa** [comment]
The tests have an example configuration: https://github.com/SAM-IT/yii2-static-assets/blob/master/tests/yii2.config.php

**Comment by blancsys** [comment]
Thanks again for your help.

I have added this section to my console configuration:

```
    'modules' => [
        'staticAssets' => [
            'class' => \SamIT\Yii2\StaticAssets\Module::class,
        ],
    ],
```

But I get this:

```
$ ./yii staticAssets/assets/publish build12345

Exception 'yii\base\InvalidConfigException' with message 'Failed to instantiate component or class "SamIT\Yii2\StaticAssets\Module".'

in /home/developer/Code/horizon/vendor/yiisoft/yii2/di/Container.php:433

Stack trace:
#0 /home/developer/Code/horizon/vendor/yiisoft/yii2/di/Container.php(365): yii\di\Container->getDependencies('SamIT\\Yii2\\Stat...')
#1 /home/developer/Code/horizon/vendor/yiisoft/yii2/di/Container.php(156): yii\di\Container->build('SamIT\\Yii2\\Stat...', Array, Array)
#2 /home/developer/Code/horizon/vendor/yiisoft/yii2/BaseYii.php(349): yii\di\Container->get('SamIT\\Yii2\\Stat...', Array, Array)
#3 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Module.php(427): yii\BaseYii::createObject(Array, Array)
#4 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Module.php(586): yii\base\Module->getModule('staticAssets')
#5 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Module.php(522): yii\base\Module->createController('assets/publish')
#6 /home/developer/Code/horizon/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('staticAssets/as...', Array)
#7 /home/developer/Code/horizon/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('staticAssets/as...', Array)
#8 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#9 /home/developer/Code/horizon/yii(20): yii\base\Application->run()
#10 {main}
```

I guess that something is wrong with my setup, I will try to understand why autoloading is not working in my case. Thanks again for your help.

**Comment by SamMousa** [comment]
Are you including the composer autoloader?

**Comment by blancsys** [comment]
I think so. The content of the "yii" file is the following:

```
#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
```

**Comment by SamMousa** [comment]
For now I'm assuming this is not an issue with this library (I'm using it in production for several projects).

If you figure it out feel free to send a PR to improve the docs, good luck!

**Comment by blancsys** [comment]
Thanks! I found my problem.
Until today, I was using PHP 7.0 (default version on Linux Mint 18.3). I installed your extension with composer using PHP 7.0. Then, I read an issue on this repo that says that PHP 7.1 is required (this could be a nice addition to the README file). So, I upgraded to PHP 7.1 installing all the packages required by Yii ("php requirements.php"). When I tried to execute "composer install" a minute ago I found that composer was broken: after installing php7.1-curl and php7.1-zip it worked again. So, I tried to execute this command again:

```
./yii staticAssets/assets/publish build12345
Unknown command: staticAssets/assets/publish

Did you mean "staticAssets/asset/publish"?
```
Ok, this is simply to solve (maybe a typo on your README?). So, I retried using "asset" in singular. This is what I get:

```
./yii staticAssets/asset/publish build12345
Publishing default bundle to webroot...
PHP Warning 'yii\base\ErrorException' with message 'mkdir(): No such file or directory'

in /home/developer/Code/horizon/vendor/sam-it/yii2-static-assets/src/controllers/AssetController.php:64

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleError(2, 'mkdir(): No suc...', '/home/developer...', 64, Array)
#1 /home/developer/Code/horizon/vendor/sam-it/yii2-static-assets/src/controllers/AssetController.php(64): mkdir('build12345/defa...')
#2 [internal function]: SamIT\Yii2\StaticAssets\controllers\AssetController->actionPublish('build12345')
#3 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#4 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#5 /home/developer/Code/horizon/vendor/yiisoft/yii2/console/Controller.php(148): yii\base\Controller->runAction('publish', Array)
#6 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Module.php(528): yii\console\Controller->runAction('publish', Array)
#7 /home/developer/Code/horizon/vendor/yiisoft/yii2/console/Application.php(180): yii\base\Module->runAction('staticAssets/as...', Array)
#8 /home/developer/Code/horizon/vendor/yiisoft/yii2/console/Application.php(147): yii\console\Application->runAction('staticAssets/as...', Array)
#9 /home/developer/Code/horizon/vendor/yiisoft/yii2/base/Application.php(386): yii\console\Application->handleRequest(Object(yii\console\Request))
#10 /home/developer/Code/horizon/yii(20): yii\base\Application->run()
#11 {main}
```
I will try to figure out why this error occurs. I guess that some config is missing on my side. Thanks again.

**Comment by SamMousa** [comment]
The webroot parent dir could be missing.

**Comment by blancsys** [comment]
Thanks. I found that I need to create the directory in advance. So, I did "mkdir runtime/build12345". And tried again:

```
developer@horiz ~/Code/horizon $ ./yii staticAssets/asset/publish runtime/build12345
Publishing default bundle to webroot...
runtime/build12345Creating asset path: runtime/build12345... OK
Publishing application assets... Autoloading: Doctrine\Common\Cache\Cache
Parsing file: /home/developer/Code/horizon/vendor/aws/aws-sdk-php/src/DoctrineCacheAdapter.phpPHP Fatal error:  Aws\DoctrineCacheAdapter cannot implement Doctrine\Common\Cache\Cache - it is not an interface in /home/developer/Code/horizon/vendor/aws/aws-sdk-php/src/DoctrineCacheAdapter.php on line 6
PHP Fatal Error 'yii\base\ErrorException' with message 'Aws\DoctrineCacheAdapter cannot implement Doctrine\Common\Cache\Cache - it is not an interface'

in /home/developer/Code/horizon/vendor/aws/aws-sdk-php/src/DoctrineCacheAdapter.php:6

Stack trace:
#0 [internal function]: yii\base\ErrorHandler->handleFatalError()
#1 {main}
```

I will check this error. I'm making progress thanks to your help :)

**Comment by SamMousa** [comment]
You'll have to use the blacklist configuration for that.
This module works by scanning PHP files to see if they are Yii2 asset bundles.
If your source directory contains broken code it won't work.
Another advantage of the blacklist is that it'll speed up the build, since you can be pretty sure for example that the whole `aws/aws-sdk-php` folder will never contain a Yii2 asset bundle.

Here's a list I use in another project:
```php
'excludedPatterns' => [
                '*/tests/*',
                '*/Tests/*',
                '*/test/*',
                '*/vendor/cebe/markdown*',
                '*/vendor/jane-php*',
                '*/vendor/sabre*',
                '*/vendor/sendgrid*',
                '*/vendor/codeception*',
                '*/vendor/docker-php*',
                '*/vendor/facebook*',
                '*/vendor/google*',
                '*/vendor/monolog*',
                '*/vendor/myclabs*',
                '*/vendor/nette*',
                '*/vendor/nesbot*',
                '*/vendor/phar-io*',
                '*/vendor/phpunit*',
                '*/vendor/rmrevin*',
                '*/vendor/sebastian*',
                '*/vendor/sendgrid*',
                '*/vendor/symfony*',
                '*/vendor/twig*',
                '*/vendor/yiisoft/yii2-composer*',
                '*/vendor/yiisoft/yii2-httpclient*',
            ],
```

**Comment by blancsys** [comment]
Thank you very much! I have added a similar configuration (based on my setup) and it worked!

```
    'modules' => [
        'staticAssets' => [
            'class' => \SamIT\Yii2\StaticAssets\Module::class,
            'excludedPatterns' => [
                '*/tests/*',
                '*/vendor/aws/*',
                [... etc ...]
                '*/vendor/cebe/markdown*',
                '*/vendor/codeception/*',
                '*/vendor/composer/*',
                '*/vendor/docker-php/*',
                '*/vendor/phpspec/*',
                '*/vendor/phpunit/*',
                '*/vendor/psr/*',
                '*/vendor/sebastian*',
                '*/vendor/setasign*',
                '*/vendor/symfony*',
                '*/vendor/yiisoft/yii2-composer*',
                '*/vendor/yiisoft/yii2-httpclient*',
            ]
        ],
    ],
```

So, the output was:

```
$ ./yii staticAssets/asset/publish runtime/build12345
Publishing default bundle to webroot...
Creating asset path: runtime/build12345... OK
Publishing application assets... Autoloading: yii\bootstrap4\Nav
Parsing file: /home/developer/Code/horizon/vendor/kartik-v/yii2-nav-x/src/NavXBs4.phpAutoloading: yii\bootstrap4\Alert
Parsing file: /home/developer/Code/horizon/vendor/kartik-v/yii2-widget-alert/src/Bs4Alert.phpOK
Publishing vendor assets... OK
Compressing assets... OK
```

Thank you very much!

**Comment by blancsys** [comment]
I guess that I need to reconfigure the [Asset Manager](https://www.yiiframework.com/doc/api/2.0/yii-web-assetmanager) to use "ReadOnlyAssetManager" and my runtime/build12345 bundle as target, but not sure how. I will try to figure out.

**Comment by blancsys** [comment]
Where should I add the "runtime/build12345" reference in the web.php config file?

```
       // Custom AssetManager
        'assetManager' => [
            'class' => \SamIT\Yii2\StaticAssets\ReadOnlyAssetManager::class,
            'assetDevelopmentMode' => false,
        
        ],
```

Thanks
